---

name: application-build

on:
  push:
    branches:
    - main
    - image
    paths:
    - "compute/**"
    - ".github/workflows/image.yml"
  pull_request:
    branches:
      - master
    paths:
    - "compute/**"
    - ".github/workflows/image.yml"


jobs:
  lint:
    defaults:
      run:
        working-directory: ./compute/app
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
        stable: false
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

  test:
    defaults:
      run:
        working-directory: ./compute/app
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: go test -v -covermode=count

  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compute/app
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Calc coverage
      run: |
        go test -v -covermode=count -coverprofile=coverage.out
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
      with:
        working-directory: ./compute/app
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./compute/app/coverage.lcov
  build:
    runs-on: ubuntu-latest
    needs: [coverage, test, lint]
    name: Build App
    defaults:
      run:
        working-directory: ./compute
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: 1.15.x
    - run: make build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: arm-build
        path: |
          ./compute/bin/
  ami:
    runs-on: ubuntu-latest
    needs: build
    name: Build App
    defaults:
      run:
        working-directory: compute/image
    steps:
    - name: Terraform Plan Status
      if: github.ref != 'refs/heads/main'
      run: exit 1
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: arm-build
        path: compute/image/tmp
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
        role-duration-seconds: 1200
        role-session-name: MySessionName
    - name: Use latest Packer
      uses: hashicorp-contrib/setup-packer@v1
    - name: Build AMI
      run: packer build ami.json
